export const ActionTypes = {
    ALL_TASKS_REQUEST: "ALL_TASKS_REQUEST",
    ALL_TASKS_SUCCESS: "ALL_TASKS_SUCCESS",
    ALL_TASKS_FAIL: "ALL_TASKS_FAIL",

    TASK_DETAIL_REQUEST: "TASK_DETAIL_REQUEST",
    TASK_DETAIL_SUCCESS: "TASK_DETAIL_SUCCESS",
    TASK_DETAIL_FAIL: "TASK_DETAIL_FAIL",

    TASK_UPDATE_REQUEST: "TASK_UPDATE_REQUEST",
    TASK_UPDATE_SUCCESS: "TASK_UPDATE_SUCCESS",
    TASK_UPDATE_FAIL: "TASK_UPDATE_FAIL",
    TASK_UPDATE_RESET: "TASK_UPDATE_RESET",

    NEW_TASK_REQUEST: "NEW_TASK_REQUEST",
    NEW_TASK_SUCCESS: "NEW_TASK_SUCCESS",
    NEW_TASK_FAIL: "NEW_TASK_FAIL",
    NEW_TASK_RESET: "NEW_TASK_RESET",
    TASK_UPDATE_RESET: "TASK_UPDATE_RESET",

    DELETE_TASK_REQUEST: "DELETE_TASK_REQUEST",
    DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
    DELETE_TASK_FAIL: "DELETE_TASK_FAIL",
    DELETE_TASK_RESET: "DELETE_TASK_RESET",


    CLEAR_ERRORS: "CLEAR_ERRORS"
}